name: Node.js CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Clone the Repository
      - name: Checkout Code
        uses: actions/checkout@v4

      # Setup Node
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: npm

      # Install Dependencies
      - name: Install dependencies
        run: npm ci

      # Compliles TypeScript and build
      - name: Build Project
        run: npm run build

      # Run Test Cases
      - name: Run Test Cases
        run: npm run test
