name: Node.js CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Clone the Repository
      - name: Checkout Code
        uses: actions/checkout@v4

      # Setup Node
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: false

      # Install Dependencies for API Gateway and Microservices
      - name: Install dependencies for API Gateway
        run: |
          cd api-gateway
          npm ci

      # Install Dependencies for Each Microservice (if they are in separate folders) Later

      # Compile TypeScript for API Gateway and Microservices
      - name: Build API Gateway and Microservices
        run: |
          cd api-gateway
          npm run build

      # Run Test Cases for API Gateway and Microservices
      - name: Run Test Cases
        run: |
          cd api-gateway
          npm run test
